### ISSUE TITLE
Additional method in ISirenListener

### ISSUE THREAD

**Issue by tylerbwoodridge** [eggheadgames/Siren#18]
Is it possible to add another method to the ISirenListener? This method would be along the lines of "onNoAction" or "onNoUpdateAvailable".

I am hoping to check my app's version while in the splash screen. After the version has been checked, I would like to verify my stored api token's validity and take the user to 1 of 2 possible activities. With the current listener methods, I am not seeing a clear way to get this behavior when the user already has the most up to date version available. Maybe I am missing something though?

Thanks!

**Comment by mikemee** [comment]
@tylerbwoodridge Hi, that's an interesting idea. I'm reading the code the same way as you - there's no way to do this currently. 

Our overall approach has been to mirror the [iOS version](https://github.com/ArtSabintsev/Siren) as closely as possible. A quick look now suggests they don't have this, so my inclination is to leae it alone. 

Alternatively, can you just track that you received no result from the `ISirenListener`?  I.e. have a timeout or similar?  Remember also that there are other reasons it can return nothing - e.g. not enough time has elapsed to check again (or, of course, no internet).

**Comment by Pantkowsky** [comment]
Hey @mikemee ! I have the same problem as the author. Has this type of callback been implemented? Problem is (as mentioned above), due to our API schema, we need to check for the version before the user actually gets into the app (check needs to happen in splash screen), otherwise bad things will happen. If the user is on the latest version, he should be allowed to enter and re-directed to appropriate activity within the app, else show the update dialog. Without the callback, the dialog will appear, but the next activity will be started meanwhile too, which is a unwanted behavior -> there is a need for additional `ISirenListener` method like `onLatestVersion` or alike. How could that be achieved?

**Comment by mikemee** [comment]
The problem with doing this in a splash screen is that there’s a server call in the middle. As those are inherently async, it seems architecturally wrong to have your splash screen wait for that.  Or maybe I’m missing something?

**Comment by Pantkowsky** [comment]
Well, you are right obviously, however I believe that this is irrelevant for the topic. Whether it is the intention of an engineer to put it in Splash screen or not should not be the decisive factor of this callback implementation. Unless I am completely wrong?

**Comment by mikemee** [comment]
@Pantkowsky True of course :)  

Hmm, ok!  Easy enough I guess, and now that two people have asked for it.  Re-opening.

I'll accept a PR (with a test) if someone is keen!
