### ISSUE TITLE
Getting tons of SSL timeout

### ISSUE THREAD

**Issue by saraht129** [eggheadgames/Siren#44]
I've implemented this to my React Native app for a while now but I've just recently added logs on the SirenListener to monitor user conversion. I was surprised by tons of SSL handshake / connection timeout errors.

I couldn't reproduce the issue on my device, however, and I'm certain that my JSON endpoint has a valid SSL cert. (We have other endpoints on the same server and we've been using it without issue on the RN side).

It's possible that our CA might not be trusted by the Android system, because this is among the logs:
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Is there anyway I can load the cert and set a custom `SSLSocketFactory`? Or is there anything else I should look at?

**Comment by mikemee** [comment]
@saraht129 I'm sorry but I have no idea! You're definitely deeper in than I've looked (our own server was not https). However, people are using https for sure. These might be relevant and/or at least help you find the code involved. Note also that there are variations based on the version of Android you're testing on:

#10 - SSL Handshake issues
#11 - Force TLS on HttpsURLConnection
#14 - Crash caused when json file is access via http (instead of https)

@bre7 Any suggestions for @saraht129, as it seems you were using https (and contributed in this area, thank you!)

**Comment by bre7** [comment]
Mmmh, I've had no issues whatsoever with HTTPS. I'll be sure to keep an eye out just in case and report back

**Comment by mikemee** [comment]
No news back. Closing this for now.
